kind: Namespace
apiVersion: v1
metadata:
  name: oger
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oger
  namespace: oger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oger
  template:
    metadata:
      labels:
        app: oger
    spec:
      containers:
        - name: oger
          image: quay.io/rlehmann/oger
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: oger
  namespace: oger
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: oger
  type: ClusterIP
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: oger-door-trigger
  namespace: default
spec:
  broker: default
  filter:
    attributes:
      type: knock-on-door
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: oger
      namespace: oger
---
